export default 
// 20230613110318
// https://api.github.com/users/NaveenMS45/followers

[
  {
    "login": "dirambora",
    "id": 42798758,
    "node_id": "MDQ6VXNlcjQyNzk4NzU4",
    "avatar_url": "https://avatars.githubusercontent.com/u/42798758?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dirambora",
    "html_url": "https://github.com/dirambora",
    "followers_url": "https://api.github.com/users/dirambora/followers",
    "following_url": "https://api.github.com/users/dirambora/following{/other_user}",
    "gists_url": "https://api.github.com/users/dirambora/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dirambora/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dirambora/subscriptions",
    "organizations_url": "https://api.github.com/users/dirambora/orgs",
    "repos_url": "https://api.github.com/users/dirambora/repos",
    "events_url": "https://api.github.com/users/dirambora/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dirambora/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "RAM-BHARATH",
    "id": 68635752,
    "node_id": "MDQ6VXNlcjY4NjM1NzUy",
    "avatar_url": "https://avatars.githubusercontent.com/u/68635752?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/RAM-BHARATH",
    "html_url": "https://github.com/RAM-BHARATH",
    "followers_url": "https://api.github.com/users/RAM-BHARATH/followers",
    "following_url": "https://api.github.com/users/RAM-BHARATH/following{/other_user}",
    "gists_url": "https://api.github.com/users/RAM-BHARATH/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/RAM-BHARATH/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/RAM-BHARATH/subscriptions",
    "organizations_url": "https://api.github.com/users/RAM-BHARATH/orgs",
    "repos_url": "https://api.github.com/users/RAM-BHARATH/repos",
    "events_url": "https://api.github.com/users/RAM-BHARATH/events{/privacy}",
    "received_events_url": "https://api.github.com/users/RAM-BHARATH/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "kartikey5565",
    "id": 78528979,
    "node_id": "MDQ6VXNlcjc4NTI4OTc5",
    "avatar_url": "https://avatars.githubusercontent.com/u/78528979?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kartikey5565",
    "html_url": "https://github.com/kartikey5565",
    "followers_url": "https://api.github.com/users/kartikey5565/followers",
    "following_url": "https://api.github.com/users/kartikey5565/following{/other_user}",
    "gists_url": "https://api.github.com/users/kartikey5565/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kartikey5565/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kartikey5565/subscriptions",
    "organizations_url": "https://api.github.com/users/kartikey5565/orgs",
    "repos_url": "https://api.github.com/users/kartikey5565/repos",
    "events_url": "https://api.github.com/users/kartikey5565/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kartikey5565/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "22388o",
    "id": 83122757,
    "node_id": "MDQ6VXNlcjgzMTIyNzU3",
    "avatar_url": "https://avatars.githubusercontent.com/u/83122757?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/22388o",
    "html_url": "https://github.com/22388o",
    "followers_url": "https://api.github.com/users/22388o/followers",
    "following_url": "https://api.github.com/users/22388o/following{/other_user}",
    "gists_url": "https://api.github.com/users/22388o/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/22388o/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/22388o/subscriptions",
    "organizations_url": "https://api.github.com/users/22388o/orgs",
    "repos_url": "https://api.github.com/users/22388o/repos",
    "events_url": "https://api.github.com/users/22388o/events{/privacy}",
    "received_events_url": "https://api.github.com/users/22388o/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Ramanan20",
    "id": 83200824,
    "node_id": "MDQ6VXNlcjgzMjAwODI0",
    "avatar_url": "https://avatars.githubusercontent.com/u/83200824?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Ramanan20",
    "html_url": "https://github.com/Ramanan20",
    "followers_url": "https://api.github.com/users/Ramanan20/followers",
    "following_url": "https://api.github.com/users/Ramanan20/following{/other_user}",
    "gists_url": "https://api.github.com/users/Ramanan20/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Ramanan20/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Ramanan20/subscriptions",
    "organizations_url": "https://api.github.com/users/Ramanan20/orgs",
    "repos_url": "https://api.github.com/users/Ramanan20/repos",
    "events_url": "https://api.github.com/users/Ramanan20/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Ramanan20/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Yogananth-r",
    "id": 88841859,
    "node_id": "MDQ6VXNlcjg4ODQxODU5",
    "avatar_url": "https://avatars.githubusercontent.com/u/88841859?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Yogananth-r",
    "html_url": "https://github.com/Yogananth-r",
    "followers_url": "https://api.github.com/users/Yogananth-r/followers",
    "following_url": "https://api.github.com/users/Yogananth-r/following{/other_user}",
    "gists_url": "https://api.github.com/users/Yogananth-r/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Yogananth-r/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Yogananth-r/subscriptions",
    "organizations_url": "https://api.github.com/users/Yogananth-r/orgs",
    "repos_url": "https://api.github.com/users/Yogananth-r/repos",
    "events_url": "https://api.github.com/users/Yogananth-r/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Yogananth-r/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "cumsoft",
    "id": 97250816,
    "node_id": "U_kgDOBcvuAA",
    "avatar_url": "https://avatars.githubusercontent.com/u/97250816?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/cumsoft",
    "html_url": "https://github.com/cumsoft",
    "followers_url": "https://api.github.com/users/cumsoft/followers",
    "following_url": "https://api.github.com/users/cumsoft/following{/other_user}",
    "gists_url": "https://api.github.com/users/cumsoft/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/cumsoft/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/cumsoft/subscriptions",
    "organizations_url": "https://api.github.com/users/cumsoft/orgs",
    "repos_url": "https://api.github.com/users/cumsoft/repos",
    "events_url": "https://api.github.com/users/cumsoft/events{/privacy}",
    "received_events_url": "https://api.github.com/users/cumsoft/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Akash7007",
    "id": 100037085,
    "node_id": "U_kgDOBfZx3Q",
    "avatar_url": "https://avatars.githubusercontent.com/u/100037085?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Akash7007",
    "html_url": "https://github.com/Akash7007",
    "followers_url": "https://api.github.com/users/Akash7007/followers",
    "following_url": "https://api.github.com/users/Akash7007/following{/other_user}",
    "gists_url": "https://api.github.com/users/Akash7007/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Akash7007/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Akash7007/subscriptions",
    "organizations_url": "https://api.github.com/users/Akash7007/orgs",
    "repos_url": "https://api.github.com/users/Akash7007/repos",
    "events_url": "https://api.github.com/users/Akash7007/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Akash7007/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "vigneshvicky77",
    "id": 100062784,
    "node_id": "U_kgDOBfbWQA",
    "avatar_url": "https://avatars.githubusercontent.com/u/100062784?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/vigneshvicky77",
    "html_url": "https://github.com/vigneshvicky77",
    "followers_url": "https://api.github.com/users/vigneshvicky77/followers",
    "following_url": "https://api.github.com/users/vigneshvicky77/following{/other_user}",
    "gists_url": "https://api.github.com/users/vigneshvicky77/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vigneshvicky77/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vigneshvicky77/subscriptions",
    "organizations_url": "https://api.github.com/users/vigneshvicky77/orgs",
    "repos_url": "https://api.github.com/users/vigneshvicky77/repos",
    "events_url": "https://api.github.com/users/vigneshvicky77/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vigneshvicky77/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Krishnakanthgv",
    "id": 101104061,
    "node_id": "U_kgDOBga5vQ",
    "avatar_url": "https://avatars.githubusercontent.com/u/101104061?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Krishnakanthgv",
    "html_url": "https://github.com/Krishnakanthgv",
    "followers_url": "https://api.github.com/users/Krishnakanthgv/followers",
    "following_url": "https://api.github.com/users/Krishnakanthgv/following{/other_user}",
    "gists_url": "https://api.github.com/users/Krishnakanthgv/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Krishnakanthgv/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Krishnakanthgv/subscriptions",
    "organizations_url": "https://api.github.com/users/Krishnakanthgv/orgs",
    "repos_url": "https://api.github.com/users/Krishnakanthgv/repos",
    "events_url": "https://api.github.com/users/Krishnakanthgv/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Krishnakanthgv/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Kabilanp4",
    "id": 104247633,
    "node_id": "U_kgDOBjaxUQ",
    "avatar_url": "https://avatars.githubusercontent.com/u/104247633?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Kabilanp4",
    "html_url": "https://github.com/Kabilanp4",
    "followers_url": "https://api.github.com/users/Kabilanp4/followers",
    "following_url": "https://api.github.com/users/Kabilanp4/following{/other_user}",
    "gists_url": "https://api.github.com/users/Kabilanp4/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Kabilanp4/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Kabilanp4/subscriptions",
    "organizations_url": "https://api.github.com/users/Kabilanp4/orgs",
    "repos_url": "https://api.github.com/users/Kabilanp4/repos",
    "events_url": "https://api.github.com/users/Kabilanp4/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Kabilanp4/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "JCSIVO",
    "id": 104387283,
    "node_id": "U_kgDOBjjS0w",
    "avatar_url": "https://avatars.githubusercontent.com/u/104387283?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/JCSIVO",
    "html_url": "https://github.com/JCSIVO",
    "followers_url": "https://api.github.com/users/JCSIVO/followers",
    "following_url": "https://api.github.com/users/JCSIVO/following{/other_user}",
    "gists_url": "https://api.github.com/users/JCSIVO/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/JCSIVO/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/JCSIVO/subscriptions",
    "organizations_url": "https://api.github.com/users/JCSIVO/orgs",
    "repos_url": "https://api.github.com/users/JCSIVO/repos",
    "events_url": "https://api.github.com/users/JCSIVO/events{/privacy}",
    "received_events_url": "https://api.github.com/users/JCSIVO/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "rithickrithu",
    "id": 104910375,
    "node_id": "U_kgDOBkDOJw",
    "avatar_url": "https://avatars.githubusercontent.com/u/104910375?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rithickrithu",
    "html_url": "https://github.com/rithickrithu",
    "followers_url": "https://api.github.com/users/rithickrithu/followers",
    "following_url": "https://api.github.com/users/rithickrithu/following{/other_user}",
    "gists_url": "https://api.github.com/users/rithickrithu/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rithickrithu/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rithickrithu/subscriptions",
    "organizations_url": "https://api.github.com/users/rithickrithu/orgs",
    "repos_url": "https://api.github.com/users/rithickrithu/repos",
    "events_url": "https://api.github.com/users/rithickrithu/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rithickrithu/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "kalaiyarasn2002454",
    "id": 105370346,
    "node_id": "U_kgDOBkfS6g",
    "avatar_url": "https://avatars.githubusercontent.com/u/105370346?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kalaiyarasn2002454",
    "html_url": "https://github.com/kalaiyarasn2002454",
    "followers_url": "https://api.github.com/users/kalaiyarasn2002454/followers",
    "following_url": "https://api.github.com/users/kalaiyarasn2002454/following{/other_user}",
    "gists_url": "https://api.github.com/users/kalaiyarasn2002454/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kalaiyarasn2002454/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kalaiyarasn2002454/subscriptions",
    "organizations_url": "https://api.github.com/users/kalaiyarasn2002454/orgs",
    "repos_url": "https://api.github.com/users/kalaiyarasn2002454/repos",
    "events_url": "https://api.github.com/users/kalaiyarasn2002454/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kalaiyarasn2002454/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Zuber8960",
    "id": 108560774,
    "node_id": "U_kgDOBniBhg",
    "avatar_url": "https://avatars.githubusercontent.com/u/108560774?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Zuber8960",
    "html_url": "https://github.com/Zuber8960",
    "followers_url": "https://api.github.com/users/Zuber8960/followers",
    "following_url": "https://api.github.com/users/Zuber8960/following{/other_user}",
    "gists_url": "https://api.github.com/users/Zuber8960/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Zuber8960/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Zuber8960/subscriptions",
    "organizations_url": "https://api.github.com/users/Zuber8960/orgs",
    "repos_url": "https://api.github.com/users/Zuber8960/repos",
    "events_url": "https://api.github.com/users/Zuber8960/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Zuber8960/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "mathivetri",
    "id": 125651127,
    "node_id": "U_kgDOB31Itw",
    "avatar_url": "https://avatars.githubusercontent.com/u/125651127?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mathivetri",
    "html_url": "https://github.com/mathivetri",
    "followers_url": "https://api.github.com/users/mathivetri/followers",
    "following_url": "https://api.github.com/users/mathivetri/following{/other_user}",
    "gists_url": "https://api.github.com/users/mathivetri/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mathivetri/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mathivetri/subscriptions",
    "organizations_url": "https://api.github.com/users/mathivetri/orgs",
    "repos_url": "https://api.github.com/users/mathivetri/repos",
    "events_url": "https://api.github.com/users/mathivetri/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mathivetri/received_events",
    "type": "User",
    "site_admin": false
  }
]