export default {
  login: "NaveenMS45",
  id: 90043520,
  node_id: "MDQ6VXNlcjkwMDQzNTIw",
  avatar_url: "https://avatars.githubusercontent.com/u/90043520?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/NaveenMS45",
  html_url: "https://github.com/NaveenMS45",
  followers_url: "https://api.github.com/users/NaveenMS45/followers",
  following_url:
    "https://api.github.com/users/NaveenMS45/following{/other_user}",
  gists_url: "https://api.github.com/users/NaveenMS45/gists{/gist_id}",
  starred_url: "https://api.github.com/users/NaveenMS45/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/NaveenMS45/subscriptions",
  organizations_url: "https://api.github.com/users/NaveenMS45/orgs",
  repos_url: "https://api.github.com/users/NaveenMS45/repos",
  events_url: "https://api.github.com/users/NaveenMS45/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/NaveenMS45/received_events",
  type: "User",
  site_admin: false,
  name: "NAVEEN MS",
  company: "Intern at Edureka !..",
  blog: "https://naveenms45.github.io/Portfolio/",
  location: "TAMIL NADU,  INDIA.",
  email: null,
  hireable: null,
  bio: "I am a highly competent Full-Stack Developer with a proven track record in designing websites and managing Databases. ",
  twitter_username: "IamMS2001",
  public_repos: 66,
  public_gists: 0,
  followers: 16,
  following: 53,
  created_at: "2021-09-03T11:45:39Z",
  updated_at: "2023-06-12T13:05:29Z",
};